"""logger_type_column_size_increase

Revision ID: 58880535a847
Revises: f1520387f181
Create Date: 2025-09-21 12:36:13.511236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58880535a847'
down_revision: Union[str, Sequence[str], None] = 'f1520387f181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ux_alias_entry_unique'), table_name='acronym_aliases')
    op.drop_table('acronym_aliases')
    op.drop_index(op.f('ix_logger_event_datetime'), table_name='document_resolution_api_logger')
    op.drop_index(op.f('ix_logger_reqid_datetime'), table_name='document_resolution_api_logger')
    op.drop_table('document_resolution_api_logger')
    op.drop_index(op.f('ix_pkg_logger_event_datetime'), table_name='document_resolution_pkg_logger')
    op.drop_table('document_resolution_pkg_logger')
    op.drop_index(op.f('ix_glossary_entries_lower_acronym'), table_name='glossary_entries')
    op.drop_table('glossary_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_entries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('glossary_entries_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('acronym', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_glossary_entries'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_glossary_entries_lower_acronym'), 'glossary_entries', [sa.literal_column('lower(acronym::text)')], unique=False)
    op.create_table('document_resolution_pkg_logger',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('level_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level_name', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('logger_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('function_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('keyword_arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_resolution_pkg_logger'))
    )
    op.create_index(op.f('ix_pkg_logger_event_datetime'), 'document_resolution_pkg_logger', ['event', 'date_time'], unique=False)
    op.create_table('document_resolution_api_logger',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_ip', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('key_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('level_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level_name', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('logger_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('function_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('keyword_arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('status IS NULL OR status >= 100 AND status <= 599', name=op.f('ck_document_resolution_api_logger_ck_logger_http_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_resolution_api_logger'))
    )
    op.create_index(op.f('ix_logger_reqid_datetime'), 'document_resolution_api_logger', ['request_id', 'date_time'], unique=False)
    op.create_index(op.f('ix_logger_event_datetime'), 'document_resolution_api_logger', ['event', 'date_time'], unique=False)
    op.create_table('acronym_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['glossary_entries.id'], name=op.f('fk_acronym_aliases_entry_id_glossary_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acronym_aliases'))
    )
    op.create_index(op.f('ux_alias_entry_unique'), 'acronym_aliases', ['entry_id', 'alias'], unique=True)
    # ### end Alembic commands ###
