"""add cols

Revision ID: 62803360bd86
Revises: 966a71ce5f83
Create Date: 2026-02-25 20:27:31.572307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62803360bd86'
down_revision: Union[str, Sequence[str], None] = '966a71ce5f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    op.add_column('glossary_entries', sa.Column('provenance', sa.String(length=128), nullable=True))
    op.drop_index(op.f('ix_glossary_entries_lower_acronym'), table_name='glossary_entries')
    op.create_index('ux_glossary_entries_lower_acronym', 'glossary_entries', [sa.literal_column('lower(acronym)')], unique=True, schema='document_resolution')
    op.drop_column('glossary_entries', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glossary_entries', sa.Column('source', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index('ux_glossary_entries_lower_acronym', table_name='glossary_entries', schema='document_resolution')
    op.create_index(op.f('ix_glossary_entries_lower_acronym'), 'glossary_entries', [sa.literal_column('lower(acronym::text)')], unique=False)
    op.drop_column('glossary_entries', 'provenance')
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
