"""create api abuse tbls

Revision ID: 7f3e2cd680e3
Revises: b721644554f6
Create Date: 2026-03-14 22:51:16.602773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f3e2cd680e3'
down_revision: Union[str, Sequence[str], None] = 'b721644554f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_daily',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['document_resolution.api_keys.id'], name=op.f('fk_api_usage_daily_api_key_id_api_keys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage_daily')),
    schema='document_resolution'
    )
    op.create_index(op.f('ix_document_resolution_api_usage_daily_api_key_id'), 'api_usage_daily', ['api_key_id'], unique=False, schema='document_resolution')
    op.create_index('uq_api_usage_daily_api_key_id_usage_date', 'api_usage_daily', ['api_key_id', 'usage_date'], unique=True, schema='document_resolution')
    op.create_table('api_usage_minute',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('minute_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['document_resolution.api_keys.id'], name=op.f('fk_api_usage_minute_api_key_id_api_keys'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage_minute')),
    schema='document_resolution'
    )
    op.create_index(op.f('ix_document_resolution_api_usage_minute_api_key_id'), 'api_usage_minute', ['api_key_id'], unique=False, schema='document_resolution')
    op.create_index('uq_api_usage_minute_api_key_id_minute_bucket', 'api_usage_minute', ['api_key_id', 'minute_bucket'], unique=True, schema='document_resolution')
    op.add_column('api_keys', sa.Column('daily_quota', sa.Integer(), nullable=True))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('ix_document_resolution_glossary_meaning_acronym_id'), table_name='glossary_meanings')
    op.create_index(op.f('ix_document_resolution_glossary_meanings_acronym_id'), 'glossary_meanings', ['acronym_id'], unique=False, schema='document_resolution')
    op.drop_constraint(op.f('fk_glossary_meaning_acronym_id_glossary_acronyms'), 'glossary_meanings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_meanings_acronym_id_glossary_acronyms'), 'glossary_meanings', 'glossary_acronyms', ['acronym_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', 'glossary_acronyms', ['acronym_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', 'glossary_acronyms', ['acronym_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_glossary_meanings_acronym_id_glossary_acronyms'), 'glossary_meanings', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_meaning_acronym_id_glossary_acronyms'), 'glossary_meanings', 'glossary_acronyms', ['acronym_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_resolution_glossary_meanings_acronym_id'), table_name='glossary_meanings', schema='document_resolution')
    op.create_index(op.f('ix_document_resolution_glossary_meaning_acronym_id'), 'glossary_meanings', ['acronym_id'], unique=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=True)
    op.drop_column('api_keys', 'daily_quota')
    op.drop_index('uq_api_usage_minute_api_key_id_minute_bucket', table_name='api_usage_minute', schema='document_resolution')
    op.drop_index(op.f('ix_document_resolution_api_usage_minute_api_key_id'), table_name='api_usage_minute', schema='document_resolution')
    op.drop_table('api_usage_minute', schema='document_resolution')
    op.drop_index('uq_api_usage_daily_api_key_id_usage_date', table_name='api_usage_daily', schema='document_resolution')
    op.drop_index(op.f('ix_document_resolution_api_usage_daily_api_key_id'), table_name='api_usage_daily', schema='document_resolution')
    op.drop_table('api_usage_daily', schema='document_resolution')
    # ### end Alembic commands ###
