"""adding api_key table

Revision ID: ae7a99bbeaa9
Revises: 62803360bd86
Create Date: 2026-02-26 11:02:23.087961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae7a99bbeaa9'
down_revision: Union[str, Sequence[str], None] = '62803360bd86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('key_id', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_id', name=op.f('uq_api_keys_key_id')),
    schema='document_resolution'
    )
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.drop_table('api_keys', schema='document_resolution')
    # ### end Alembic commands ###
