"""create api abuse tbls

Revision ID: b93894d26409
Revises: 7f3e2cd680e3
Create Date: 2026-03-14 22:57:09.493568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93894d26409'
down_revision: Union[str, Sequence[str], None] = '7f3e2cd680e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_api_usage_daily_api_key_id_api_keys'), 'api_usage_daily', type_='foreignkey')
    op.create_foreign_key(op.f('fk_api_usage_daily_api_key_id_api_keys'), 'api_usage_daily', 'api_keys', ['api_key_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_api_usage_minute_api_key_id_api_keys'), 'api_usage_minute', type_='foreignkey')
    op.create_foreign_key(op.f('fk_api_usage_minute_api_key_id_api_keys'), 'api_usage_minute', 'api_keys', ['api_key_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_glossary_meanings_acronym_id_glossary_acronyms'), 'glossary_meanings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_meanings_acronym_id_glossary_acronyms'), 'glossary_meanings', 'glossary_acronyms', ['acronym_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    op.drop_constraint(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', 'glossary_acronyms', ['acronym_id'], ['id'], source_schema='document_resolution', referent_schema='document_resolution', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), 'glossary_variants', 'glossary_acronyms', ['acronym_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_glossary_meanings_acronym_id_glossary_acronyms'), 'glossary_meanings', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_glossary_meanings_acronym_id_glossary_acronyms'), 'glossary_meanings', 'glossary_acronyms', ['acronym_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_api_usage_minute_api_key_id_api_keys'), 'api_usage_minute', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_api_usage_minute_api_key_id_api_keys'), 'api_usage_minute', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_api_usage_daily_api_key_id_api_keys'), 'api_usage_daily', schema='document_resolution', type_='foreignkey')
    op.create_foreign_key(op.f('fk_api_usage_daily_api_key_id_api_keys'), 'api_usage_daily', 'api_keys', ['api_key_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
