"""logger nullable fields adjusted

Revision ID: 139540ade42f
Revises: 668bcce5b0db
Create Date: 2025-08-28 10:52:42.505684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139540ade42f'
down_revision: Union[str, Sequence[str], None] = '668bcce5b0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], source_schema='unacronym', referent_schema='unacronym', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', schema='unacronym', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
