"""baseline

Revision ID: 20bf798c82fb
Revises: 
Create Date: 2025-08-26 08:46:05.919707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bf798c82fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_entries',
    sa.Column('acronym', sa.String(length=64), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_entries'))
    )
    op.create_index('ix_glossary_entries_lower_acronym', 'glossary_entries', [sa.literal_column('lower(acronym)')], unique=False)
    op.create_table('acronym_aliases',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['glossary_entries.id'], name=op.f('fk_acronym_aliases_entry_id_glossary_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acronym_aliases'))
    )
    op.create_index('ux_alias_entry_unique', 'acronym_aliases', ['entry_id', 'alias'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_alias_entry_unique', table_name='acronym_aliases')
    op.drop_table('acronym_aliases')
    op.drop_index('ix_glossary_entries_lower_acronym', table_name='glossary_entries')
    op.drop_table('glossary_entries')
    # ### end Alembic commands ###
