"""basline

Revision ID: aa653f93bb86
Revises: 
Create Date: 2025-09-14 16:28:51.571262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa653f93bb86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acronym', sa.String(length=64), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_entries')),
    schema='unacronym'
    )
    op.create_index('ix_glossary_entries_lower_acronym', 'glossary_entries', [sa.literal_column('lower(acronym)')], unique=False, schema='unacronym')
    op.create_table('unacronym_api_logger',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('key_id', sa.String(length=128), nullable=True),
    sa.Column('level_code', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('logger_type', sa.String(length=32), nullable=False),
    sa.Column('function_name', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('status IS NULL OR (status BETWEEN 100 AND 599)', name=op.f('ck_unacronym_api_logger_ck_logger_http_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unacronym_api_logger')),
    schema='unacronym'
    )
    op.create_index('ix_logger_event_datetime', 'unacronym_api_logger', ['event', 'date_time'], unique=False, schema='unacronym')
    op.create_index('ix_logger_reqid_datetime', 'unacronym_api_logger', ['request_id', 'date_time'], unique=False, schema='unacronym')
    op.create_table('acronym_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['unacronym.glossary_entries.id'], name=op.f('fk_acronym_aliases_entry_id_glossary_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acronym_aliases')),
    schema='unacronym'
    )
    op.create_index('ux_alias_entry_unique', 'acronym_aliases', ['entry_id', 'alias'], unique=True, schema='unacronym')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_alias_entry_unique', table_name='acronym_aliases', schema='unacronym')
    op.drop_table('acronym_aliases', schema='unacronym')
    op.drop_index('ix_logger_reqid_datetime', table_name='unacronym_api_logger', schema='unacronym')
    op.drop_index('ix_logger_event_datetime', table_name='unacronym_api_logger', schema='unacronym')
    op.drop_table('unacronym_api_logger', schema='unacronym')
    op.drop_index('ix_glossary_entries_lower_acronym', table_name='glossary_entries', schema='unacronym')
    op.drop_table('glossary_entries', schema='unacronym')
    # ### end Alembic commands ###
