"""normalise glossary

Revision ID: b721644554f6
Revises: ae7a99bbeaa9
Create Date: 2026-03-04 21:14:35.835036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b721644554f6'
down_revision: Union[str, Sequence[str], None] = 'ae7a99bbeaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_acronyms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('acronym', sa.String(length=64), nullable=False),
    sa.Column('normalized', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_acronyms')),
    schema='unacronym'
    )
    op.create_index('ix_glossary_acronyms_active_normalized', 'glossary_acronyms', ['normalized'], unique=False, schema='unacronym', postgresql_where=sa.text('is_active IS true'))
    op.create_index('ix_glossary_acronyms_normalized', 'glossary_acronyms', ['normalized'], unique=False, schema='unacronym')
    op.create_index('ux_glossary_acronyms_tenant_normalized', 'glossary_acronyms', ['tenant_id', 'normalized'], unique=True, schema='unacronym')
    op.create_table('glossary_meaning',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('acronym_id', sa.BigInteger(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('provenance', sa.String(length=128), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acronym_id'], ['unacronym.glossary_acronyms.id'], name=op.f('fk_glossary_meaning_acronym_id_glossary_acronyms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_meaning')),
    schema='unacronym'
    )
    op.create_index('ix_glossary_meaning_acronym_active', 'glossary_meaning', ['acronym_id', 'is_active'], unique=False, schema='unacronym')
    op.create_index(op.f('ix_unacronym_glossary_meaning_acronym_id'), 'glossary_meaning', ['acronym_id'], unique=False, schema='unacronym')
    op.create_index('ux_glossary_meaning_acronym_domain', 'glossary_meaning', ['acronym_id', 'domain'], unique=True, schema='unacronym')
    op.create_table('glossary_variants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('acronym_id', sa.BigInteger(), nullable=False),
    sa.Column('variant', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acronym_id'], ['unacronym.glossary_acronyms.id'], name=op.f('fk_glossary_variants_acronym_id_glossary_acronyms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_variants')),
    schema='unacronym'
    )
    op.create_index('ix_glossary_variant_lower_variant', 'glossary_variants', [sa.literal_column('lower(variant)')], unique=False, schema='unacronym')
    op.create_index(op.f('ix_unacronym_glossary_variants_acronym_id'), 'glossary_variants', ['acronym_id'], unique=False, schema='unacronym')
    op.create_index('ux_glossary_variant_acronym_lower_variant', 'glossary_variants', ['acronym_id', sa.literal_column('lower(variant)')], unique=True, schema='unacronym')
    # 1) drop FK dependents first
    op.drop_table("acronym_aliases")
    # 2) then drop the parent
    op.drop_table("glossary_entries")
    op.create_index(
        "ix_glossary_acronyms_active_normalized",
        "glossary_acronyms",
        ["normalized"],
        unique=False,
        postgresql_where=sa.text("is_active IS TRUE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acronym_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['glossary_entries.id'], name=op.f('fk_acronym_aliases_entry_id_glossary_entries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acronym_aliases'))
    )
    op.create_index(op.f('ux_alias_entry_unique'), 'acronym_aliases', ['entry_id', 'alias'], unique=True)
    op.create_table('glossary_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('acronym', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('provenance', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_entries'))
    )
    op.create_index(op.f('ux_glossary_entries_lower_acronym'), 'glossary_entries', [sa.literal_column('lower(acronym::text)')], unique=True)
    op.drop_index('ux_glossary_variant_acronym_lower_variant', table_name='glossary_variants', schema='unacronym')
    op.drop_index(op.f('ix_unacronym_glossary_variants_acronym_id'), table_name='glossary_variants', schema='unacronym')
    op.drop_index('ix_glossary_variant_lower_variant', table_name='glossary_variants', schema='unacronym')
    op.drop_table('glossary_variants', schema='unacronym')
    op.drop_index('ux_glossary_meaning_acronym_domain', table_name='glossary_meaning', schema='unacronym')
    op.drop_index(op.f('ix_unacronym_glossary_meaning_acronym_id'), table_name='glossary_meaning', schema='unacronym')
    op.drop_index('ix_glossary_meaning_acronym_active', table_name='glossary_meaning', schema='unacronym')
    op.drop_table('glossary_meaning', schema='unacronym')
    op.drop_index('ux_glossary_acronyms_tenant_normalized', table_name='glossary_acronyms', schema='unacronym')
    op.drop_index('ix_glossary_acronyms_normalized', table_name='glossary_acronyms', schema='unacronym')
    op.drop_index('ix_glossary_acronyms_active_normalized', table_name='glossary_acronyms', schema='unacronym', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('glossary_acronyms', schema='unacronym')
    # ### end Alembic commands ###
