"""logger_table

Revision ID: c1e663a245ba
Revises: 6942d21df00b
Create Date: 2025-09-04 07:43:45.943852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1e663a245ba'
down_revision: Union[str, Sequence[str], None] = '6942d21df00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logger',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('level_code', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('logger_type', sa.String(length=32), nullable=False),
    sa.Column('function_name', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('key_id', sa.String(length=128), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logger')),
    schema='unacronym'
    )
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], source_schema='unacronym', referent_schema='unacronym', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', schema='unacronym', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.drop_table('logger', schema='unacronym')
    # ### end Alembic commands ###
