"""unacronym logger two

Revision ID: f1520387f181
Revises: 963d8ef426d6
Create Date: 2025-09-14 17:26:30.953447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1520387f181'
down_revision: Union[str, Sequence[str], None] = '963d8ef426d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unacronym_pkg_logger',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('level_code', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=128), nullable=False),
    sa.Column('logger_type', sa.String(length=32), nullable=False),
    sa.Column('function_name', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyword_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unacronym_pkg_logger')),
    schema='unacronym'
    )
    op.create_index('ix_pkg_logger_event_datetime', 'unacronym_pkg_logger', ['event', 'date_time'], unique=False, schema='unacronym')
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], source_schema='unacronym', referent_schema='unacronym', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', schema='unacronym', type_='foreignkey')
    op.create_foreign_key(op.f('fk_acronym_aliases_entry_id_glossary_entries'), 'acronym_aliases', 'glossary_entries', ['entry_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_pkg_logger_event_datetime', table_name='unacronym_pkg_logger', schema='unacronym')
    op.drop_table('unacronym_pkg_logger', schema='unacronym')
    # ### end Alembic commands ###
